[tool.poetry]
name = "jacc-hammer"
version = "0.1.0"
description = "Python library for fuzzy matching large data sets."
license = "MIT"
readme = "README.md"
homepage = "https://github.com/nestauk/jacc-hammer"
repository = "https://github.com/nestauk/jacc-hammer"
authors = ["bishax <alex.bishop@nesta.org.uk>"]

[tool.poetry.dependencies]
python = "^3.6"
pandas = "0.25"
joblib = "^0.14.1"
numpy = "^1.18.1"
scipy = "^1.4.1"
tqdm = "^4.43.0"
cytoolz = "^0.10.1"
datasketch = "^1.5.0"
fuzzywuzzy = "^0.18.0"
scikit-learn = "^0.22.2"
nltk = "^3.4.5"
python-Levenshtein = "^0.12.0"
cython = "^0.29.15"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
